server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://0.0.0.0:8761/eureka/

logging:
  level:
    com.netflix.discovery: 'ON'
    org.springframework.cloud.gateway: 'TRACE'

---

spring:
  profiles: docker

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

logging:
  level:
    com.netflix.discovery: 'ON'
    org.springframework.cloud.gateway: 'TRACE'



